dist: precise

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

matrix:
    fast_finish: true

install:
    - composer install

script: phpunit -c tests/phpunit.xml.dist --coverage-clover=coverage.clover

before_script:
    - mysql -uroot -e 'create database if not exists phpunit_garden;'

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    hipchat:
        rooms:
            secure: "hm1gLERnItWUbRBq4hnxA4UbD2/e0RZCSVwWh80ku89dIkJ2xKcI+N+mBSya5opqGYZNXBf4KM0dzpqZa4uNDx1OMZJa/LDWGJ5idnHZcKd5+eyAoNY1ZKTWvUhZB7x3C3OH2e2O/Qumgw1gpho2OS7NR/SkT3GkvLLwfy5vKGc="
        template:
            - >
                Build <a href="%{build_url}">#%{build_number}</a>
                (<a href="%{compare_url}">%{commit}</a>)
                of <a href="https://github.com/%{repository}/tree/%{branch}">%{repository}@%{branch}</a>
                by %{author}: %{message}
        format: html
    slack:
        secure: "UiaqXaJaudbD0m6+1azWIkZ6fTHAr87WUCIcFh48S5UXDn5Gy0EKHLH2ANAGG4UizVjyJxg8bnYn9XAX+V9Oanau783wEyWb8EDbIzA9Lvp23hLcsHfkT1u3Oia3dhjHGBOg4oA0YB/60WE63Wa3r2W6jMD4Sl5hZJ9jEC1Zukk="
